apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog
  template:
    metadata:
      labels:
        app: dog
    spec:
      containers:
      - name: dog
        image: docker.io/mtmazurik/devopsgenie-service:latest
        imagePullPolicy: Always
        ports:
        - name: dog-port
          containerPort: 80
        env:
          - name: DOGREPONOOK_URI
            valueFrom:
              secretKeyRef:
                name: dog-svc-reponook-uri-info 
                key: dog-reponook-uri
          - name: DOGREPONOOK_PORT
            valueFrom:
              secretKeyRef:
                name: dog-svc-reponook-uri-info
                key: dog-reponook-port
          - name: DO_ENCRYPT
            valueFrom:
              secretKeyRef:
                name: dog-svc-encryption-info
                key: dog-do-encrypt
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: dog-svc-encryption-info
                key: dog-encryption-key
        livenessProbe:
          httpGet:
            path: /admin/ping
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/ping
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30